on: [push, pull_request]

name: windows path silliness

jobs:
  native:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"
          use-public-rspm: true
      - name: Install renv package
        run: |
          Rscript -e 'install.packages("renv")'
      - name: Print system path
        run: |
          echo "Current PATH:"
          echo $env:PATH
      - name: Update PATH with R directory
        run: |            
          # Create bin path
          $rDir = "C:\Program Files\R\R-latest"
          $binPath = Join-Path $rDir "bin"
          echo "R bin directory: $binPath"
          
          # If C:\R exists, move its contents (this requires admin privileges in normal circumstances)
          if (Test-Path "C:\R") {
              Move-Item -Path "C:\R\*" -Destination "$rDir" -Force
          } else {
              echo "C:\R folder not found"
          }
          
          # Add the new path to the PATH environment variable (prepending to give it priority)
          $newPath = "$binPath;" + $env:PATH
          echo "PATH=$newPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          echo "Updated PATH to include $binPath"
      - name: Verify updated PATH
        run: |
          echo "Updated PATH:"
          echo $env:PATH
      - name: Sys.info
        run: |
          Rscript -e 'Sys.info()'
      - name: Get R binary path
        run: |
          "C:\Program Files\R\R-latest\bin\Rscript.exe" -e 'cat("R binary path:", file.path(R.home("bin"), "R.exe"), "\n")'
          "C:\Program Files\R\R-latest\bin\Rscript.exe" -e 'cat("R home directory:", R.home(), "\n")'
          "C:\Program Files\R\R-latest\bin\Rscript.exe" -e 'cat("R version:", R.version$version.string, "\n")'