on: [push, pull_request]

name: windows path silliness

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"
          use-public-rspm: true
      - name: Install renv package
        run: |
          Rscript -e 'install.packages("renv")'
      - name: Print system path
        run: |
          echo "Current PATH:"
          echo $env:PATH