on: [push, pull_request]

name: windows path silliness

jobs:
  native:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"
          use-public-rspm: true
      - name: Install renv package
        run: |
          Rscript -e 'install.packages("renv")'
      - name: Print system path
        run: |
          echo "Current PATH:"
          echo $env:PATH
      - name: List C:\Program Files contents
        run: |
          echo "Contents of C:\Program Files:"
          Get-ChildItem -Path "C:\Program Files" -Recurse | Select-Object FullName