on: [push, pull_request]

name: windows path silliness

jobs:
  native:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "latest"
          use-public-rspm: true
      - name: Install renv package
        run: |
          Rscript -e 'install.packages("renv")'
      - name: Print system path
        run: |
          echo "Current PATH:"
          echo $env:PATH
      - name: Update PATH with R directory
        run: |            
          # Create bin path
          $rDir = "C:\Program Files\R\R-latest"
          $binPath = Join-Path $rDir "bin"
          echo "R bin directory: $binPath"
          
          # If C:\R exists, move its contents (this requires admin privileges in normal circumstances)
          if (Test-Path "C:\R") {
              Move-Item -Path "C:\R\*" -Destination "$rDir" -Force

              echo "Files after move in destination directory ($rDir):"
              Get-ChildItem -Path "$rDir" -Recurse | Select-Object -ExpandProperty FullName
          } else {
              echo "C:\R folder not found"
          }
          
          # Add the new path to the PATH environment variable (prepending to give it priority)
          $newPath = "$rDir;" + $env:PATH
          echo "PATH=$newPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
          echo "Updated PATH to include $rDir"
      - name: Verify updated PATH
        run: |
          echo "Updated PATH:"
          echo $env:PATH
      - name: Sys.info
        run: |
          Rscript -e 'Sys.info()'
      - name: Get R binary path
        run: |
          # First check if the Rscript.exe exists at the expected path
          $rscriptPath = "C:\Program Files\R\R-latest\bin\Rscript.exe"
          if (Test-Path $rscriptPath) {
              echo "Found Rscript at expected path: $rscriptPath"
              & $rscriptPath -e 'cat("R binary path:", file.path(R.home("bin"), "R.exe"), "\n")'
              & $rscriptPath -e 'cat("R home directory:", R.home(), "\n")'
              & $rscriptPath -e 'cat("R version:", R.version$version.string, "\n")'
          } else {
              echo "Rscript not found at expected path. Trying with which.exe or where.exe..."
              $whereRscript = where.exe Rscript 2>$null
              if ($whereRscript) {
              echo "Found Rscript at: $whereRscript"
              Rscript -e 'cat("R binary path:", file.path(R.home("bin"), "R.exe"), "\n")'
              Rscript -e 'cat("R home directory:", R.home(), "\n")'
              Rscript -e 'cat("R version:", R.version$version.string, "\n")'
              } else {
              echo "ERROR: Could not find Rscript.exe in PATH"
              echo "Current PATH: $env:PATH"
              echo "Available directories in C:\Program Files\R:"
              Get-ChildItem "C:\Program Files\R" -ErrorAction SilentlyContinue | Format-Table Name, FullName
              }
          }